### ISSUE TITLE
NoConnectionPendingException in UT

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#111]
Hudson's output

Running org.deftserver.io.AsynchronousSocketTest
19:16:54.581 [I/O-LOOP] DEBUG org.deftserver.io.AsynchronousSocket - handle connect...
    Exception in thread "I/O-LOOP" java.nio.channels.NoConnectionPendingException
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:559)
    at org.deftserver.io.AsynchronousSocket.handleConnect(AsynchronousSocket.java:92)
    at org.deftserver.io.IOLoop.start(IOLoop.java:79)
    at org.deftserver.io.AsynchronousSocketTest$1.run(AsynchronousSocketTest.java:33)
    at java.lang.Thread.run(Thread.java:662)
    waiting for client...
    client connected..

About NCPE:
"Unchecked exception thrown when the finishConnect method of a SocketChannel is invoked without first successfully invoking its connect method. "

**Comment by rschildmeijer** [comment]
closed in https://github.com/rschildmeijer/deft/commit/7fc69fc3230a435ab0eca704e1c1894810f9ec8b
