### ISSUE TITLE
Support for "Transfer-Encoding: chunked" in AsynchronousHttpClient

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#116]
http://en.wikipedia.org/wiki/Chunked_transfer_encoding
http://www.jmarshall.com/easy/http/#http1.1c2

**Comment by rschildmeijer** [comment]
http://weblog.rubyonrails.org/2011/4/18/why-http-streaming

**Comment by rschildmeijer** [comment]
client fetch "http://sunet.se/" (good candidate to test Transfer-Encoding: chunked on) produces the following stacktrace (due to lack of chunked support):

Exception in thread "I/O-LOOP" java.lang.NumberFormatException: null
    at java.lang.Integer.parseInt(Integer.java:417)
    at java.lang.Integer.parseInt(Integer.java:499)
    at org.deftserver.web.http.client.AsynchronousHttpClient.onHeaders(AsynchronousHttpClient.java:180)
    at org.deftserver.web.http.client.AsynchronousHttpClient.access$5(AsynchronousHttpClient.java:170)
    at org.deftserver.web.http.client.AsynchronousHttpClient$4.onSuccess(AsynchronousHttpClient.java:166)
    at org.deftserver.web.http.client.AsynchronousHttpClient$4.onSuccess(AsynchronousHttpClient.java:1)
    at org.deftserver.io.AsynchronousSocket.invokeReadSuccessfulCallback(AsynchronousSocket.java:199)
    at org.deftserver.io.AsynchronousSocket.checkReadState(AsynchronousSocket.java:186)
    at org.deftserver.io.AsynchronousSocket.handleRead(AsynchronousSocket.java:136)
    at org.deftserver.io.IOLoop.start(IOLoop.java:84)
    at org.deftserver.example.AsynchronousHttpClientExample.main(AsynchronousHttpClientExample.java:28)
