### ISSUE TITLE
ConcurrentModificationException in JMXDebuggableTimeoutManager?

### ISSUE THREAD

**Issue by 1730wang** [rschildmeijer/deft#143]
Exception in thread "I/O-LOOP" java.util.ConcurrentModificationException
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1100)
        at java.util.TreeMap$EntryIterator.next(TreeMap.java:1136)
        at java.util.TreeMap$EntryIterator.next(TreeMap.java:1131)
        at com.google.common.collect.AbstractMapBasedMultiset$EntrySet$1.next(Ab  stractMapBasedMultiset.java:112)
        at com.google.common.collect.AbstractMapBasedMultiset$EntrySet$1.next(Ab  stractMapBasedMultiset.java:102)
        at com.google.common.collect.Multisets.addAllImpl(Multisets.java:497)
        at com.google.common.collect.AbstractMultiset.addAll(AbstractMultiset.ja  va:114)
        at com.google.common.collect.TreeMultiset.addAll(TreeMultiset.java:51)
        at com.google.common.collect.Iterables.addAll(Iterables.java:272)
        at com.google.common.collect.TreeMultiset.create(TreeMultiset.java:104)
        at org.deftserver.io.timeout.JMXDebuggableTimeoutManager.execute(JMXDebu  ggableTimeoutManager.java:55)
        at org.deftserver.io.IOLoop.start(IOLoop.java:64)

o_o

**Comment by rschildmeijer** [comment]
what version are you running?

**Comment by 1730wang** [comment]
I don't know, it's from the zip file my friend sent me. I assume it's the latest version?

**Comment by rschildmeijer** [comment]
The latest Deft release (0.3.0,https://github.com/downloads/rschildmeijer/deft/deft-0.3.0-binary-with-deps.zip,  released April 21, 2011) has the following fix: https://github.com/rschildmeijer/deft/issues/89
Make sure you are running that one and report back if you still see the CME. If you do, please attach a code snippet that reproduces the exception :)

**Comment by 1730wang** [comment]
False alarm. I used an older version.

**Comment by rschildmeijer** [comment]
np
